# Generated by Django 3.2.8 on 2022-11-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_basketitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
