# Generated by Django 3.2.8 on 2022-11-29 13:25

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_historyitem_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyitem',
            name='picture',
        ),
        migrations.AddField(
            model_name='historyitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.image_directory_path),
        ),
    ]
