# Generated by Django 3.2.8 on 2022-11-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20221129_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyitem',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
