# Generated by Django 3.2.8 on 2022-11-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(default=2, max_length=1500, verbose_name='name'),
            preserve_default=False,
        ),
    ]
