# Generated by Django 3.2.8 on 2022-11-19 19:01

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=store.models.image_directory_path)),
            ],
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='followers',
            new_name='items_no',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='date_published',
        ),
        migrations.AddField(
            model_name='basket',
            name='date_made',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date made'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='name',
            field=models.TextField(max_length=1500, verbose_name='basket_name'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='picture',
        ),
        migrations.CreateModel(
            name='HistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1500, verbose_name='history_name')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('picture', models.ManyToManyField(related_name='history_image', to='store.ImageFiles')),
            ],
        ),
        migrations.AddField(
            model_name='basketitem',
            name='picture',
            field=models.ManyToManyField(related_name='_basket_image', to='store.ImageFiles'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ManyToManyField(related_name='image', to='store.ImageFiles'),
        ),
    ]
